### ISSUE TITLE
Happy Birthday & Mac Support

### ISSUE THREAD

**Issue by Ben348** [AmyJeanes/HomeAutomation#1]
A little but loud birdy told me it was your birthday so HAPPY BIRTHDAY good sir! I hope you had a great day and most importantly I hope you got a MacBook so you can finally start supporting all environments.

Speaking of which, is there a timeline for when you expect the first OSX release to be?

**Comment by AmyJeanes** [comment]
Hi @Ben348 thank you for your kind words. The app is using Docker and therefore already works on macOS - I hope you find this news pleasing.
